insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO )
values (1001, 65, '', 'USD', 'INR');
insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO )
values (1003, 65, '', 'EUR', 'INR');
insert into CURRENCY_EXCHANGE (ID, CONVERSION_MULTIPLE, ENVIRONMENT, CURRENCY_FROM, CURRENCY_TO )
values (1004, 65, '', 'AUD', 'INR');